name: 'Action run in background'
description: 'Run stuff in the background'
icon: arrow-up
color: purple
inputs:
  script:
    description: 'The script to run in background.'
    required: true
  readiness-script:
    description: 'The script that tells whether of not the process is ready/health.'
    required: true
  shell:
    description: 'The type of the shell that should be called.'
    required: false
    default: 'bash'
  timeout:
    description: 'Max time in seconds to wait for readiness.'
    required: false
    default: 120
# outputs:
#   pid:
#     description: 'the pid of the spawned process'
runs:
  using: 'node20'
  main: 'dist/index.js'
