name: Lint and Test

on:
    push:
        branches: '*'

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint-and-format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 20
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: 'Check code formatting'
              run: |
                  pnpm i
                  pnpm run format-check

    test:
        runs-on: ubuntu-latest
        needs: [lint-and-format]
        steps:
            - uses: actions/checkout@v4
            - name: 'Setup container'
              run: |
                  sudo apt update
                  sudo apt install ca-certificates curl gnupg -y

            - name: 'Setup Docker'
              run: |
                  curl -fsSL https://get.docker.com -o get-docker.sh
                  sudo chmod +x ./get-docker.sh
                  sudo ./get-docker.sh

            - name: 'Clean docker daemon'
              run: |
                  sudo pkill -f "dockerd"
                  sleep 2
                  sudo rm /var/run/docker.pid
                  docker system prune --volumes -f
                  sudo rm -f /var/lib/docker/volumes/metadata.db

            - name: 'Spin up containerd'
              run: |
                  sudo containerd &
            - uses: miguelteixeiraa/action-run-in-background@main
              with:
                  script: |
                      sudo dockerd --containerd /run/containerd/containerd.sock
                  readiness-script: |
                      if ! docker info > /dev/null 2>&1; then
                          echo "Error accessing Docker info. The Docker daemon is not ready/healthy yet."
                          exit 1
                      fi
                  shell: bash
                  timeout: 30
